routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();
Route::get('/logout', 'UserController@logout');
Route::get('/ceklogin', 'UserController@dologin')->name('dologin');

// Route::get('/import', 'ImportController@showImportPage');
// Route::post('/importCategory', 'ImportController@ImportCategory');
// Route::post('/importBrand', 'ImportController@ImportBrand');
// Route::post('/importType', 'ImportController@ImportType');
// Route::post('/importProduct', 'ImportController@ImportProduct');
// Route::post('/importCustomer', 'ImportController@ImportCustomer');
// Route::post('/updateCustomer', 'ImportController@updateCustomer');
// Route::get('/generateDo', 'DeliveryOrderController@generateDOForAllRemainingSo');


Route::group(['middleware' => 'auth'], function () {

	Route::get('/testsendmail/{id}', 'SalesInvoiceController@testMail');

  Route::get('/', 'HomeController@showMainPage');
  Route::get('/homes', 'HomeController@showHomePage');
  Route::get('/home/news','HomeController@loadhomenews');
  Route::get('/home/salesinvoicedue','HomeController@loadSalesInvoiceDue');
  Route::get('/home/stock','HomeController@loadStockOverview');
  Route::get('/home/expense','HomeController@loadExpense');
  Route::get('/home/salesachievement','HomeController@loadSalesAchievement');
  Route::get('/home/purchaseachievement','HomeController@loadPurchaseAchievement');
  Route::get('/home/accountreceiveable','HomeController@loadAccountReceiveable');
  Route::get('/home/piutang-so','HomeController@loadhomepiutangso');
  Route::get('/home/piutang-po','HomeController@loadhomepiutangpo');

	Route::get('/sendmail/{id}', 'SalesInvoiceController@sendMail');

//  Route::get('/user_profile', 'UserController@showProfilePage');
	Route::get('/user_profile', 'UserController@showProfilePage');
	Route::get('/manage_user', 'UserController@showManageUserPage');
	Route::get('/change_password', 'UserController@showChangePassword');
	Route::get('/get_account', 'UserController@getAccountData');
	Route::get('/get_account_manage', 'UserController@getAccountManage');
	Route::post('/update_account', 'UserController@updateAccount');
	Route::post('/update_account_manage', 'UserController@updateAccountManage');
	Route::post('/create_account', 'UserController@createAccount');
	Route::post('/update_password', 'UserController@changePassword');
	Route::post('/delete_account', 'UserController@deleteAccount');

  Route::get('/pelanggan', 'PelangganController@showPelangganPage');
  Route::get('/getpelanggantable', 'PelangganController@getPelangganTable');
  Route::get('/getPelangganData', 'PelangganController@getPelangganData');
  Route::get('/getCashHistoryTransaction', 'PelangganController@getCashHistoryTransaction');
  Route::get('/getCreditHistoryTransaction', 'PelangganController@getCreditHistoryTransaction');
  Route::get('/validPelangganPhone', 'PelangganController@validPelangganPhone');
  Route::get('/validPelangganNik', 'PelangganController@validPelangganNik');
  Route::get('/modalPelangganData', 'PelangganController@modalPelangganData');
  Route::get('/getcustomerbalance', 'PelangganController@getCustomerBalance');
  Route::get('/getPelangganInfo', 'PelangganController@getPelangganInfo');
  Route::get('/deletePelanggan', 'PelangganController@deletePelanggan');
	Route::post('/createPelanggan', 'PelangganController@createPelanggan');
	Route::post('/updatePelanggan', 'PelangganController@updatePelanggan');
	Route::post('/blockPelanggan', 'PelangganController@blockPelanggan');
	Route::post('/unblockPelanggan', 'PelangganController@unblockPelanggan');
	Route::get('/balance', 'PelangganController@showBalancePage');
  Route::get('/detail-balance', 'PelangganController@showBalanceDetail');

  Route::get('/supplier', 'SupplierController@showSupplierPage');
  Route::get('/getSupplierData', 'SupplierController@getSupplierData');
  Route::get('/filterSupplier', 'SupplierController@filterSupplier');
  Route::get('/modalSupplierData', 'SupplierController@modalSupplierData');
  Route::get('/deleteSupplier', 'SupplierController@deleteSupplier');
  Route::post('/createSupplier', 'SupplierController@createSupplier');
  Route::post('/updateSupplier', 'SupplierController@updateSupplier');

  Route::get('/target', 'SupplierController@showTargetPage');
  Route::post('/createtarget', 'SupplierController@createTarget');

  Route::get('/kategoribarang', 'KategoriBarangController@showKategoriBarangPage');
  Route::get('/getKategoriData', 'KategoriBarangController@getKategoriData');
  Route::get('/modalKategoriData', 'KategoriBarangController@modalkategoriData');
  Route::get('/deleteKategoriBarang', 'KAtegoriBarangController@deleteKategoriBarang');
  Route::post('/createKategoriBarang', 'KategoriBarangController@createKategoriBarang');
  Route::post('/updateKategoriBarang', 'KategoriBarangController@updateKategoriBarang');

  Route::get('/brandbarang', 'BrandBarangController@showBrandBarangPage');
  Route::get('/getbrandtable', 'BrandBarangController@getBrandTable');
  Route::get('/getBrandData', 'BrandBarangController@getBrandData');
  Route::get('/getBrandOnKategori', 'BrandBarangController@getBrandOnKategori');
  Route::get('/modalBrandData', 'BrandBarangController@modalBrandData');
  Route::get('/deleteBrandBarang', 'BrandBarangController@deleteBrandBarang');
  Route::post('/createBrandBarang', 'BrandBarangController@createBrandBarang');
  Route::post('/updateBrandBarang', 'BrandBarangController@updateBrandBarang');

  Route::get('/tipebarang', 'TipeBarangController@showTipeBarangPage');
  Route::get('/gettipetable', 'TipeBarangController@getTipeTable');
  Route::get('/getTipeData', 'TipeBarangController@getTipeData');
  Route::get('/getTipeOnBrand', 'TipeBarangController@getTipeOnBrand');
  Route::get('/getKategoriOnBrand', 'TipeBarangController@getKategoriOnBrand');
  Route::get('/modalTipeData', 'TipeBarangController@modalTipeData');
  Route::get('/deleteTipeBarang', 'TipeBarangController@deleteTipeBarang');
  Route::post('/createTipeBarang', 'TipeBarangController@createTipeBarang');
  Route::post('/createTipeBarangFromPo', 'TipeBarangController@createTipeBarangFromPo');
  Route::post('/updateTipeBarang', 'TipeBarangController@updateTipeBarang');

  Route::get('/barang', 'BarangController@showBarangPage');
  Route::get('/getBarangData', 'BarangController@getBarangData');
  Route::get('/getBarangUseBarcode', 'BarangController@getBarangUsingBarcode');
  Route::get('/filterBarang', 'BarangController@filterBarang');
  Route::get('/modalBarangData', 'BarangController@modalBarangData');
  Route::get('/deleteBarang', 'BarangController@deleteBarang');
  Route::post('/createBarang', 'BarangController@createBarang');
  Route::post('/updateBarang', 'BarangController@updateBarang');
	Route::get('/getbaranginfo','BarangController@getBarangInfo');

  Route::get('/satuan', 'SatuanController@showSatuanPage');
  Route::get('/getSatuanData', 'SatuanController@getSatuanData');
  Route::get('/filterSatuan', 'SatuanController@filterSatuan');
  Route::get('/modalSatuanData', 'SatuanController@modalSatuanData');
  Route::get('/deleteSatuan', 'SatuanController@deleteSatuan');
  Route::post('/createSatuan', 'SatuanController@createSatuan');
  Route::post('/updateSatuan', 'SatuanController@updateSatuan');

  Route::get('/news', 'NewsController@showNewsPage');
  Route::get('/getNewsData', 'NewsController@getNewsData');
  Route::get('/filterNews', 'NewsController@filterNews');
  Route::get('/modalNewsData', 'NewsController@modalNewsData');
  Route::get('/deleteNews', 'NewsController@deleteNews');
  Route::post('/createNews', 'NewsController@createNews');
  Route::post('/updateNews', 'NewsController@updateNews');

  Route::get('/bank', 'BankController@showBankPage');
  Route::get('/getBankData', 'BankController@getBankData');
  Route::get('/modalBankData', 'BankController@modalBankData');
	Route::get('/deleteBank', 'BankController@deleteBank');
	Route::post('/createBank', 'BankController@createBank');
	Route::post('/updateBank', 'BankController@updateBank');

	Route::get('/gudang', 'GudangController@showGudangPage');
	Route::get('/getGudangData', 'GudangController@getGudangData');
	Route::get('/filterGudang', 'GudangController@filterGudang');
	Route::get('/modalGudangData', 'GudangController@modalGudangData');
	Route::get('/deleteGudang', 'GudangController@deleteGudang');
	Route::post('/createGudang', 'GudangController@createGudang');
	Route::post('/updateGudang', 'GudangController@updateGudang');

	Route::get('/levelpelanggan', 'LevelPelangganController@showLevelPelangganPage');
	Route::get('/getCustomerLevelData', 'LevelPelangganController@getCustomerLevelData');
	Route::post('/createCustomerLevel', 'LevelPelangganController@createCustomerLevel');
	Route::post('/updateCustomerLevel', 'LevelPelangganController@updateCustomerLevel');

	Route::get('/expensecategory','ExpenseCategoryController@showExpenseCategoryPage');
	Route::get('/getexpensecategorydata','ExpenseCategoryController@getExpenseCategoryData');
	Route::get('/modalexpensecategorydata', 'ExpenseCategoryController@modalExpenseCategoryData');
	Route::post('/createexpensecategory','ExpenseCategoryController@createExpenseCategory');
  Route::post('/updateexpensecategory','ExpenseCategoryController@updateExpenseCategory');
  Route::get('/deleteexpensecategory','ExpenseCategoryController@deleteExpenseCategory');

	Route::get('/shippingterm','ShippingTermController@showShippingTermPage');
	Route::get('/getshippingtermdata','ShippingTermController@getShippingTermData');

app/customer.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use DB;

class customer extends Model
{
    //
    protected $table = 'customer';
    protected $primaryKey = 'customer_id';
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'last_update';

    //Section for mutators
    public function getFullNameAttribute()
		{
			return "{$this->first_name} {$this->last_name}";
		}

		//Section for Relations
    public function so()
    {
        return $this->hasMany('App\salesorder', 'customer_id', 'customer_id')
            ->where('status', 1);
    }

    public function level()
    {
        return $this->hasOne('App\customerlevel', 'customer_level_id', 'customer_level_id')
            ->where('status', 1);
    }

    public function city()
    {
        return $this->hasOne('App\indonesiacities', 'customer_level_id', 'id');
    }

    public function payment()
    {
        return $this->hasManyThrough(
            'App\salespayment',
            'App\salesorder',
            'customer_id', // Foreign key on users table...
            'sales_order_id', // Foreign key on posts table...
            'customer_id', // Local key on countries table...
            'sales_order_id' // Local key on users table...
        );
    }

    public function unsettled_sales(){
        return $this->hasMany('App\salesorder', 'customer_id', 'customer_id')
            ->whereExists(function ($query) {
                $query->select(DB::raw(1),  DB::raw('SUM(total_paid) as total_payment'))
                    ->from('payment_sales')
                    ->leftjoin('payment_sales_details','payment_sales_details.payment_sales_id','=','payment_sales.payment_sales_id')
                    ->whereRaw('payment_sales.sales_order_id = sales_order.sales_order_id')
                    ->groupby('payment_sales.payment_sales_id')
										->where('payment_sales.status',1)
										->havingRaw("SUM(total_paid) < sales_order.grand_total_idr");
            })
            ->where('status', 1);
    }

	public function laststate(){
		return $this->hasOne('App\customerstate','customer_id','customer_id')
			->orderBy('customer_state_id','desc');
	}

	public function dueinvoice(){
    	return $this->hasManyThrough(
    		'App\salesinvoice',
				'App\salesorder',
				'customer_id',
				'sales_order_id',
				'customer_id',
				'sales_order_id'
				)->whereDate('invoice_sales.due_date','<',Carbon::now())
				->whereNull('invoice_sales.payment_sales_id')
				->where('invoice_sales.status',1);
	}
}

resources/views/city.blade.php
@foreach($cities as $key => $value)
	@if($selectedcity == $value->id)
		<option value="{{$value->id}}" selected>{{$value->name}}</option>
	@else
		<option value="{{$value->id}}">{{$value->name}}</option>
	@endif
@endforeach

resources/views/header.blade.php
<?
$date = date("d F Y, H:i");
?>
<script type="text/javascript">
  function updateclock() {
    $('#clock').html(moment().format('D. MMMM YYYY H:mm:ss'));
  }
  setInterval(updateclock, 1000);
</script>
<nav class="red darken-1">
  <div class="container-fluid">
    <div class="nav-wrapper">
      <a href="#" data-activates="slide-out" class="button-collapse left"><i class="material-icons">menu</i></a>
      <a href="#" class="brand-logo center">Ratna Boutique</a>
        {{--<div class=".center">--}}
            {{--<img src="{{asset('images/ratna.png')}}" alt="no-images">--}}
        {{--</div>--}}
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li id="clock">08 / 02 /2017 ( 11:53:46 AM )</li>
      </ul>
    </div>
  </div>
</nav>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/import.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <meta charset="utf-8">
    <title>Sistem Toko</title>
    <link rel="stylesheet" href="css/materialize.css">
    <link rel="stylesheet" href="css/datepicker.min.css">
    <link rel="stylesheet" href="css/master.css">
    <link rel="stylesheet" href="css/toastr.css">
    <link rel="stylesheet" href="css/master.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<form id="form-category">
    <div>
        <input type="file" name="category" id="category">
        <button type="button" id="submit-category">Submit Category</button>
    </div>
</form>
<form id="form-brand">
    <div>
        <input type="file" name="brand" id="brand">
        <button type="submit" id="submit-brand">Submit Brand</button>
    </div>
</form>
<form id="form-type">
    <div>
        <input type="file" name="type" id="type">
        <button type="submit" id="submit-type">Submit Type</button>
    </div>
</form>
<form id="form-product">
    <div>
        <input type="file" name="product" id="product">
        <button type="submit" id="submit-product">Submit Product</button>
    </div>
</form>
<form id="form-customer">
    <div>
        <input type="file" name="customer" id="customer">
        <button type="submit" id="submit-customer">Submit Customer</button>
    </div>
</form>
<form id="form-update">
    <div>
        <input type="file" name="update" id="update">
        <button type="submit" id="update-customer">Update Customer</button>
    </div>
</form>
<script src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/toastr.js"></script>
<script src="js/datepicker.min.js"></script>
<script src="js/datepicker.en.js"></script>
<script src="js/materialize.min.js"></script>
<script src="js/moment.js"></script>
<script>
    $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#submit-category').click(function(event){
            event.preventDefault();
            var formData = new FormData();
            jQuery.each(jQuery('#category')[0].files, function(i, v) {
                formData.append('category',v);
            });

            $.ajax({
                type:"POST",
                url:"importCategory",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success:function(response){
                    toastr.success('Category Telah Berhasil Di Import!');
                }
            });
        })
        $('#submit-brand').click(function(event){
            event.preventDefault();
            var formData = new FormData();
            jQuery.each(jQuery('#brand')[0].files, function(i, v) {
                formData.append('brand',v);
            });

            $.ajax({
                type:"POST",
                url:"importBrand",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success:function(response){
                    toastr.success('Brand Telah Berhasil Di Import!');
                }
            });
        });
        $('#submit-type').click(function(event){
            event.preventDefault();
            var formData = new FormData();
            jQuery.each(jQuery('#type')[0].files, function(i, v) {
                formData.append('type',v);
            });

            $.ajax({
                type:"POST",
                url:"importType",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success:function(response){
                    toastr.success('Type Telah Berhasil Di Import!');
                }
            });
        });

        $('#submit-product').click(function(event){
            event.preventDefault();
            var formData = new FormData();
            jQuery.each(jQuery('#product')[0].files, function(i, v) {
                formData.append('product',v);
            });

            $.ajax({
                type:"POST",
                url:"importProduct",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success:function(response){
                    toastr.success('Product Telah Berhasil Di Import!');
                }
            });
        });

        $('#submit-customer').click(function(event){
            event.preventDefault();
            var formData = new FormData();
            jQuery.each(jQuery('#customer')[0].files, function(i, v) {
                formData.append('customer',v);
            });

            $.ajax({
                type:"POST",
                url:"importCustomer",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success:function(response){
                    toastr.success('Customer Telah Berhasil Di Import!');
                }
            });
        });

        $('#update-customer').click(function(event){
            event.preventDefault();
            var formData = new FormData();
            jQuery.each(jQuery('#update')[0].files, function(i, v) {
                formData.append('update',v);
            });

            $.ajax({
                type:"POST",
                url:"updateCustomer",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success:function(response){
                    toastr.success('Customer Telah Berhasil Di Update!');
                }
            });
        });
    })
</script>
</body>
</html>

resources/views/main.blade.php
@extends('layouts.layout')

@section('content')
    @include('home.home')
@endsection

resources/views/menu.blade.php
<ul id="slide-out" class="side-nav fixed">
  <li>
    <div class="userView">
      <div class="background">
        <img src="images/office.jpg">
      </div>
      <a href="#!user">
        <img class="circle" @if(Session('user')->profile_picture) src="{{'uploads/avatars/'.Session('user')->profile_picture}}" @else src="uploads/avatars/profile.jpg" @endif>
      </a>
      <a><h6 class="white-text">{{Session('user')->full_name}} - {{Session('roles')->name}}</h6></a>
      <a href="#!email" data-activates="email-drop" class="dropdown-button"><span class="white-text email">{{Session('user')->email}}<i class="right material-icons">arrow_drop_down</i></span></a>
    </div>
    <ul id="email-drop" class="dropdown-content">
      <li><a href="logout">Logout</a></li>
    </ul>
  </li>
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <ul class="collapsible-header ">
        <li><span class="subheader">Application List</span></li>
      </ul>
      <ul class="collapsible-body">
        <li class="nav-item active"><a url="homes"><i class="material-icons">home</i>Home</a></li>
        <li class="nav-item "><a href="user_profile"><i class="material-icons">person_pin</i>User Profile</a></li>
        <li><a href="change_password"><i class="material-icons">person_pin</i>Change Password</a></li>
        @if(Session('roles')->name == 'master')
          <li><a href="manage_user"><i class="material-icons">accessibility</i>User Manage</a></li>
        @endif
        <li><a href="logout" class="nav-item"><i class="material-icons">exit_to_app</i>Logout</a></li>
      </ul>
    </li>
  </ul>
  <li class="divider"></li>
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <ul class="collapsible-header">
        <li><span class="subheader">Master</span></li>
      </ul>
      <ul class="collapsible-body">
        <li class="nav-item"><a url="pelanggan" ><i class="material-icons">people</i>Pelanggan</a></li>
        <li class="nav-item"><a url="supplier" ><i class="material-icons">add_shopping_cart</i>Supplier</a></li>
        @if(Session('roles')->name == 'master')
          <li class="nav-item"><a url="news"><i class="material-icons">trending_up</i>News</a></li>
          <li class="nav-item"><a url="bank"><i class="material-icons">attach_money</i>Bank</a></li>
          <li class="nav-item"><a url="gudang"><i class="material-icons">store</i>Warehouse</a></li>
        @endif
        @if(Session('roles')->name == 'master' || Session('roles')->name == 'Admin Purchasing')
          <li class="nav-item"><a url="kategoribarang"><i class="material-icons">donut_large</i>Kategori Barang</a></li>
          <li class="nav-item"><a url="brandbarang"><i class="material-icons">donut_large</i>Brand Barang</a></li>
          <li class="nav-item"><a url="tipebarang"><i class="material-icons">donut_large</i>Tipe Barang</a></li>
        @endif
        @if(Session('roles')->name == 'master')
          <li class="nav-item"><a url="levelpelanggan"><i class="material-icons">people</i>Level Pelanggan</a></li>
        @endif
        <li class="nav-item"><a url="expensecategory"><i class="material-icons">people</i>Kategori Expense</a></li>
        @if(Session('roles')->name == 'master')
          <li class="nav-item"><a url="shippingterm"><i class="material-icons">people</i>Shipping Term</a></li>
        @endif
      </ul>
    </li>
  </ul>
  <li class="divider"></li>
  @if(Session('roles')->name == 'master' || Session('roles')->name == 'Admin Purchasing')
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <ul class="collapsible-header">
          <li><span class="subheader">Pembelian</span></li>
        </ul>
        <ul class="collapsible-body">
          <li class="nav-item"><a url="purchaseorder"><i class="material-icons">attach_money</i>Pemesanan / PO</a></li>
          <li class="nav-item"><a url="hargajual"><i class="material-icons">attach_money</i>Input Harga Jual</a></li>
          <li class="nav-item"><a url="penerimaanbarang"><i class="material-icons">arrow_back</i>Penerimaan Barang</a></li>
          <li class="nav-item"><a url="purchaseinvoice"><i class="material-icons">assignment</i>Purchase Invoice</a></li>
          <li class="nav-item"><a url="purchasepayment"><i class="material-icons">assignment</i>Purchase Payment</a></li>
          <li class="nav-item"><a url="purchasereturn"><i class="material-icons">arrow_back</i>Purchase Return</a></li>
          <li class="nav-item"><a url="depositopayment"><i class="material-icons">arrow_back</i>Deposito Clearance</a></li>
        </ul>
      </li>
    </ul>
    <li class="divider"></li>
  @endif
  @if(Session('roles')->name == 'master' || Session('roles')->name == 'Admin Sales')
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <ul class="collapsible-header">
          <li><span class="subheader">Penjualan</span></li>
        </ul>
        <ul class="collapsible-body">
          <li class="nav-item"><a url="salesorder"><i class="material-icons">account_box</i>Sales Order</a></li>
          <li class="nav-item"><a url="deliveryorder"><i class="material-icons">account_box</i>Delivery Order</a></li>
          <li class="nav-item"><a url="salespayment"><i class="material-icons">account_box</i>Pembayaran Cicilan</a></li>
          <li class="nav-item"><a url="salesreturn"><i class="material-icons">arrow_back</i>Return Sales</a></li>
          <li class="nav-item"><a url="balancemanagement"><i class="material-icons">account_box</i>Saldo Pelanggan</a></li>
          <li class="nav-item"><a url="existingreceiveable"><i class="material-icons">short_text</i><p>Existing Receiveable</p></a></li>
        </ul>
      </li>
    </ul>
    <li class="divider"></li>
  @endif
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <ul class="collapsible-header">
        <li><span class="subheader">Stock</span></li>
      </ul>
      <ul class="collapsible-body">
        <li class="nav-item"><a url="stockoverview"><i class="material-icons">import_contacts</i>Stock Overview</a></li>
        @if(Session('roles')->name == 'master')
          <li class="nav-item"><a url="stockcorrection"><i class="material-icons">import_contacts</i>Stock Correction</a></li>
          <li class="nav-item"><a url="historystockcorrection"><i class="material-icons">import_contacts</i>History Correction</a></li>
        @endif
      </ul>
    </li>
  </ul>
  <li class="divider"></li>
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <ul class="collapsible-header">
        <li><span class="subheader">Report</span></li>
      </ul>
      <ul class="collapsible-body">
        <li class="nav-item"><a url="reportpo"><i class="material-icons">book</i>Report PO</a></li>
        <li class="nav-item"><a url="reportso"><i class="material-icons">book</i>Report SO</a></li>
        <li class="nav-item"><a url="reportpiutang"><i class="material-icons">book</i>Report Piutang</a></li>
        <li class="nav-item"><a url="reportpembayaranpiutang"><i class="material-icons">book</i><p>Report Pembayaran Piutang</p></a></li>
        <li class="nav-item"><a url="reportexpense"><i class="material-icons">book</i><p>Report Biaya Harian</p></a></li>
        @if(Session('roles')->name == 'master')
          <li class="nav-item"><a url="reportcashbalance"><i class="material-icons">book</i><p>Report Cash Balance</p></a></li>
          <li class="nav-item"><a url="reportprofitloss"><i class="material-icons">book</i><p>Report Profit Loss</p></a></li>
          <li class="nav-item"><a url="reportexistingreceiveable"><i class="material-icons">book</i><p>Report Existing Transaction</p></a></li>
        @endif
      </ul>
    </li>
  </ul>
  <li class="divider"></li>

  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <ul class="collapsible-header">
        <li><span class="subheader">Misc</span></li>
      </ul>
      <ul class="collapsible-body">
        <li class="nav-item"><a url="expense"><i class="material-icons">short_text</i><p>Expense</p></a></li>
        <li class="nav-item"><a url="followup"><i class="material-icons">short_text</i><p>Follow Up</p></a></li>
        <li class="nav-item"><a url="outstanding-receiveable"><i class="material-icons">short_text</i><p>Outstanding Receiveable</p></a></li>
      </ul>
    </li>
  </ul>
</ul>

resources/views/script.blade.php
  <script src="js/jquery.min.js"></script>

    <script src="js/materialize.min.js"></script>

    <script src="js/jquery.dataTables.min.js"></script>

    <script src="js/dcalendar.picker.js"></script>

    <script type="text/javascript" src="js/jquery.newsTicker.min.js"></script>

    <script src="js/custom.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>